name: Lightfixes CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
    tags: ['*']

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: DreamWeave-MP/StroggForge/.github/workflows/rustGlobalBuild.yml@v27
    secrets: inherit
    with:
      # Required: JSON array of binary names to build. Add more for monorepos.
      binary_names: '["s3lightfixes"]'
      cargo_publish: false
